# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.gen/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.gen/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
