# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.runs/synth_1/.Xil/Vivado-22156-LAPTOP-IGLTMBSE/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    {d:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.gen/sources_1/ip/ROM_D}
    {d:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.gen/sources_1/ip/RAM_B}
  } D:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    {d:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.gen/sources_1/ip/ROM_D}
    {d:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.gen/sources_1/ip/RAM_B}
  } {
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.runs/synth_1/.Xil/Vivado-22156-LAPTOP-IGLTMBSE/realtime/ROM_D_stub.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.runs/synth_1/.Xil/Vivado-22156-LAPTOP-IGLTMBSE/realtime/RAM_B_stub.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/Counter_3_IO.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/Detect.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/ctrl_encode_def.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/EXT.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/Enter.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/Forwarding.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/GRE_array.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/MIO_BUS.V}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/Multi_8CH32.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/NPC.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/PC.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/RF.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/SCPU.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/SPIO.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/SSeg7.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/Stall.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/alu.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/clk_div.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/ctrl.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/dm_controller.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.srcs/sources_1/new/int_controller.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.srcs/sources_1/new/int_judger.v}
      {D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/code/top.v}
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/大学/大三上/第三学期/计算机系统综合设计/complex proj1/project_1/project_1.runs/synth_1/.Xil/Vivado-22156-LAPTOP-IGLTMBSE/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
